inherit_from: .rubocop_todo.yml
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'
Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/schema.rb'
Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'
Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'
