require: rubocop-rails
inherit_from: .rubocop_todo.yml
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'
Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/schema.rb'
Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'
Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'
Style/WordArray:
  Exclude:
    - 'db/schema.rb'
Layout/LineLength:
  Exclude:
    - 'db/schema.rb'
Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'
    - 'spec/**/*_spec.rb'
