version: '3.7'

services:
  db:
    image: postgres:12.2-alpine
    restart: unless-stopped
    container_name: graphql-server-postgres
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust #Never use in production!
volumes:
  dbdata:
