default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch('SQL_DATABASE') %>
  username: <%= ENV.fetch('SQL_USERNAME') %>
  password: <%= ENV.fetch('SQL_PASSWORD') %>
  host: <%= ENV.fetch('SQL_HOST') %>
  port: <%= ENV.fetch('SQL_PORT') %>
  reconnect: true

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
