name: Docker ruby build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build --file Dockerfile --tag sushie1984/rails-graphql-server:$GITHUB_SHA .

      - name: Run rubocop on container
        run: docker run sushie1984/rails-graphql-server:$GITHUB_SHA bundle exec rubocop
